### ISSUE TITLE
Add missing possible exits

### ISSUE THREAD

**Issue by tedhudek** [tedhudek/sandbox#10]
@Thebinarymonster feel free to assign this one to yourself.

The room descriptions should include:

* southwest as an option from Front Yard
* north as an option from 20th & Forest

Affects: 

https://github.com/tedhudek/sandbox/blob/c4ac0d0863233c102b7f7fc5857d3cb911fab268/inform/story.ni#L86
https://github.com/tedhudek/sandbox/blob/c4ac0d0863233c102b7f7fc5857d3cb911fab268/inform/story.ni#L163

**Comment by Thebinarymonster** [comment]
HOW DO I EDIT IT I FORGOT WHERE THE BUTTON IS 😠😠😠

**Comment by Thebinarymonster** [comment]
![image](https://user-images.githubusercontent.com/50305948/231269558-65104f66-5dbe-4fe5-bce9-f59613ecb177.png)
yippee

**Comment by tedhudek** [comment]
Issues listed here have been fixed in #13.  Great job @Thebinarymonster!
